version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
