version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:             
      POSTGRES_PASSWORD: secret

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: secret
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
